### ISSUE TITLE
为什么 跳转路由前要获取userInfo。我去掉这个以后后台会不停的获取路由

### ISSUE THREAD

**Issue by mrchenxxx** [antdv-pro/antdv-pro#1]
![image](https://github.com/antdv-pro/antdv-pro/assets/44868578/0e8dc6d9-597a-4740-9b63-0704a96ca2c5)
![image](https://github.com/antdv-pro/antdv-pro/assets/44868578/a16e40df-7c4a-4905-96c3-e2387655c1df)

**Comment by aibayanyu20** [comment]
那你这一块儿应该改造一下判断路由是否已经存在了，如果存在就不要走这么if判断了，目前看你这里应该是一直在进这个if判断

**Comment by mrchenxxx** [comment]
> 那你这一块儿应该改造一下判断路由是否已经存在了，如果存在就不要走这么if判断了，目前看你这里应该是一直在进这个if判断

但是这个和userinfo有关系吗，我去掉这个就不停的请求，加上即便是空的，也会继续走

**Comment by aibayanyu20** [comment]
判断逻辑问题和用户信息并没有直接的关系，可以将userInfo改成routerData，判断路由信息是否存在即可

**Comment by mrchenxxx** [comment]
方便帮忙修改下吗 我实在是弄不懂了
`if ( !allowList.includes(to.path) && !to.path.startsWith('/redirect') ) {
      try {
        const currentRoute = await userStore.generateDynamicRoutes()
        await router.addRoute(currentRoute)
        next({
          ...to,
          replace: true,
        })
        return
      }
      catch (e) {
        if (e instanceof AxiosError && e?.response?.status === 401) {
          // 跳转到error页面
          next({
            path: '/401',
          })
        }
      }
    }`

**Comment by aibayanyu20** [comment]
把userStore.userInfo改成userStore.routerData

**Comment by mrchenxxx** [comment]
> 把userStore.userInfo改成userStore.routerData

谢谢，解决了，这个admin后台管理非常不错！❤😍

**Comment by aibayanyu20** [comment]
感谢支持
