### ISSUE TITLE
建议:文件命名不要都用`index.vue`,在vue devtools里面会有歧义

### ISSUE THREAD

**Issue by yzqdev** [antdv-pro/antdv-pro#100]
### 如图,如果文件命名是index.vue,那么在vuejs devtools里面显示的就是`<Index></Index>`无法准确的知道是什么组件
![file](https://github.com/antdv-pro/antdv-pro/assets/20037151/e968f60e-9fa4-46b4-8258-99456df7d4e3)

### 像`multi-tab/index.vue`这种可以改为`multi-tab.vue`或者`multi-tab/multitab.vue`,

**Comment by kirklin** [comment]
可以考虑一下用`defineOptions`

**Comment by kirklin** [comment]
```ts
defineOptions({
    name: "XXXXXXXX",
  });
```
