### ISSUE TITLE
【feature】集成自动加载本地svg图标功能

### ISSUE THREAD

**Issue by aibayanyu20** [antdv-pro/antdv-pro#105]
https://unocss.dev/presets/icons 直接使用unocss进行集成
存放svg的目录，在src/assets/icons

**Comment by wcySpring** [comment]
以增加相关配置项

**Comment by wcySpring** [comment]
要是动态svg 还是给像之前提到的

unplugin-icons vite-plugin-svg-icons @iconify/vue

集成进去虽然关于他们优缺点

unplugin-icons , 能够识别本地 svg 文件，并且可以配合 iconify 图标库，利用 unplugin-auto-import 可以实现自动下载 使用到的 iconify 图标集

vite-plugin-svg-icons, 针对本地 svg 图标插件管理，通过配合 封装的 svg 组件，利用其精灵图的特性可以优化 svg 数量

@iconify/vue,一个已经封装好的 vue 组件用来直接使用 iconify 图标库，支持cdn 加载图片，并且会将加载后的图标存储在本地，也可以使用 本地下载好的 iconify 图标库

这三种是优选，unocss 弊端是还会 增加svg 图片请求连接。小批量上来说确实 unocss 可能还算方便，但是大量切动态加载上目前我感觉是不合适的
