### ISSUE TITLE
https://www.antdv-pro.com/首次加载太慢了，是否考虑优化加载速度？

### ISSUE THREAD

**Issue by wangfei9999** [antdv-pro/antdv-pro#114]
![image](https://github.com/antdv-pro/antdv-pro/assets/73685882/a4e0e201-0584-4ccf-a72c-9a59fa09aa1d)

**Comment by aibayanyu20** [comment]
后期套国内cdn，现在国外的服务器会慢些

**Comment by wangfei9999** [comment]
好的

**Comment by aibayanyu20** [comment]
可以试一下现在的速度应该快很多了
