### ISSUE TITLE
www.antdv-pro.com/ 页面访问不了

### ISSUE THREAD

**Issue by Winna-wnn** [antdv-pro/antdv-pro#116]
![WXWorkCapture_16976198183581](https://github.com/antdv-pro/antdv-pro/assets/68949293/930bb01b-6e12-45be-a968-dc0311145355)

**Comment by aibayanyu20** [comment]
清理一下缓存试试，我这边可以正常打开

**Comment by Winna-wnn** [comment]
已正常
