### ISSUE TITLE
build 失败 plugins/index.d.ts' has not been built from source file 'plugins/index.ts'.

### ISSUE THREAD

**Issue by frankchen211** [antdv-pro/antdv-pro#121]
vite.config.ts:6:35 - error TS6305: Output file 'plugins/index.d.ts' has not been built from source file 'plugins/index.ts'.

6 import { createVitePlugins } from './plugins'

请问应该如何解决？

**Comment by aibayanyu20** [comment]
测试了一下我们的项目，没有问题的，能给提供一个复现的仓库，我们来看一下吗

**Comment by frankchen211** [comment]
> 测试了一下我们的项目，没有问题的，能给提供一个复现的仓库，我们来看一下吗

我拉了下最新代码，好像没事了……
