### ISSUE TITLE
查询表格页是否可以增加工具栏

### ISSUE THREAD

**Issue by 1974193036** [antdv-pro/antdv-pro#125]
<img width="234" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/20085991/4f0d9ded-c4ed-4f4e-8d5c-cdb62a0a2201">
<img width="262" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/20085991/425363e1-6bd1-40dd-91b6-fb6a8a85a850">

**Comment by aibayanyu20** [comment]
在计划中了

**Comment by selicens** [comment]
我做一下吧，预计周五完成

**Comment by aibayanyu20** [comment]
> 我做一下吧，预计周五完成

点个赞
