### ISSUE TITLE
文件夹为test时路由出错Bug

### ISSUE THREAD

**Issue by kuailemao** [antdv-pro/antdv-pro#131]
## 发现文件夹为test时路由设置component: '/system/test',会出现错误
**如下问题复现：** 
下面是我的文件结构
> ![image](https://github.com/antdv-pro/antdv-pro/assets/88065987/3601497e-7ad7-408c-8975-9f71c00c3d3b)

下面是我的路由配置：
> ![image](https://github.com/antdv-pro/antdv-pro/assets/88065987/c09158ed-3059-4aa3-96e6-b4527fa465b3)

前端会出现如下错误：
> ![image](https://github.com/antdv-pro/antdv-pro/assets/88065987/c5f04d94-32c0-4676-b88e-2071eac19647)

当我把文件夹的名称改为log时：
>![image](https://github.com/antdv-pro/antdv-pro/assets/88065987/1546e98a-78e5-478a-8c1f-4e48614a9469)

成功访问该路由：

> ![image](https://github.com/antdv-pro/antdv-pro/assets/88065987/400b85f8-2e0b-4aa0-809a-09649bcf7734)

我觉得这应该是底层js处理路由逻辑时的一个bug吧

**Comment by aibayanyu20** [comment]
https://github.com/antdv-pro/antdv-pro/blob/ca9d37bda9ffb66b50e50c7ceb818491970fb62f/src/router/router-modules.ts#L12

**Comment by kuailemao** [comment]
> https://github.com/antdv-pro/antdv-pro/blob/ca9d37bda9ffb66b50e50c7ceb818491970fb62f/src/router/router-modules.ts#L12
> 
> 去掉这行代码，默认是排除test目录的

好的，感谢答复
