### ISSUE TITLE
登录接口默认携带Authorization 很奇怪 不知道在哪里添加了

### ISSUE THREAD

**Issue by zoujinglong666** [antdv-pro/antdv-pro#132]
![image](https://github.com/antdv-pro/antdv-pro/assets/83895241/44e1714e-ea41-4b12-a218-12f4cad46ce2)

**Comment by zoujinglong666** [comment]
不知道在哪里清除

**Comment by aibayanyu20** [comment]
https://github.com/antdv-pro/antdv-pro/blob/ca9d37bda9ffb66b50e50c7ceb818491970fb62f/src/api/common/login.ts#L20

**Comment by zoujinglong666** [comment]
因为请求换成了自己封装的  最后发现应该是缓存问题

**Comment by aibayanyu20** [comment]
> 因为请求换成了自己封装的  最后发现应该是缓存问题

我的意思是如果不想让登陆接口带着token的话，你可以配置token为false
