### ISSUE TITLE
打包的时候报错

### ISSUE THREAD

**Issue by yooooooT** [antdv-pro/antdv-pro#138]
报错这个<script src="/_app.config.js"> in "/index.html" can't be bundled without type="module" attribute
然后vite.config.js设置了base，对于这个app.config无效 这是为什么？

**Comment by yooooooT** [comment]
这个_app.config.js打包后引用的路径可以在哪里改吗？想改成相对路径

**Comment by aibayanyu20** [comment]
为什么要相对路径

**Comment by aibayanyu20** [comment]
base一般都是绝对路径没有相对路径，如果你是请求路径是/customDir，那么base就配置/customDir

**Comment by yooooooT** [comment]
> base一般都是绝对路径没有相对路径，如果你是请求路径是/customDir，那么base就配置/customDir

我现在改成绝对路径了，像静态资源是/customDir/dist/assets/这样子，但是_app.config.js的路径没有变化 还是/_app.config.js/，_app.config.js是只能在根目录吗？

**Comment by aibayanyu20** [comment]
> > base一般都是绝对路径没有相对路径，如果你是请求路径是/customDir，那么base就配置/customDir
> 
> 我现在改成绝对路径了，像静态资源是/customDir/dist/assets/这样子，但是_app.config.js的路径没有变化 还是/_app.config.js/，_app.config.js是只能在根目录吗？

这应该是插件的bug @kirklin

**Comment by kirklin** [comment]
更新至 0.1.4即可消除警告，baseDir需要单独配置
https://github.com/kirklin/unplugin-config
