### ISSUE TITLE
顶级菜单不可以使用？ 

### ISSUE THREAD

**Issue by powerhai** [antdv-pro/antdv-pro#141]
比方讲： “表单页” 是一个顶级菜单，我想点击它的时候就路由到具体的页面上，结果显示的是一片空白。

**Comment by aibayanyu20** [comment]
https://www.antdv-pro.com/dashboard/analysis
测试了一下顶级菜单是没有问题的，可以被点击，如果你的还有问题，请提供一个复现的菜单的数据格式或者复现的具体步骤

**Comment by powerhai** [comment]
> https://www.antdv-pro.com/dashboard/analysis 测试了一下顶级菜单是没有问题的，可以被点击，如果你的还有问题，请提供一个复现的菜单的数据格式或者复现的具体步骤


谢谢大佬回复！ 

可能我没说清楚，我是说： “一个没有子菜单的根菜单不能有效的导航到页面” ， 因为我想点击菜单就显示出页面，不想去点伸缩三角弹出子菜单。 

以下是我添加的代码，供重现：

**在 server/routes/menu/index.ts 中的menuData中添加一项：**

```
{
    id: 85,
    parentId: null,
    title: '商铺管理',
    icon: 'DashboardOutlined',
    component: '/shop', 
    path: '/shop',
    name: 'Shop',  
    locale: 'menu.shop',
  },
```

**> 在src/router/dynamic-routes.ts 中添加一项：**

```
{
    path: '/shop', 
    name: 'Shop',
    meta: {
      title: '商铺管理',
      icon: 'UserOutlined',  
      locale: 'menu.shop',
    },
    component: () => import('~/pages/shop/ShopIndex.vue'), 
    children:[],
  }
```

**> 创建 src/page/shop/ShopIndex.vue**

```
 <script setup lang="ts">

</script>

<template>
  <div>
    商铺管理系统
  </div>
</template>
```

**Comment by powerhai** [comment]
请忽略，是我自己错了。

**Comment by powerhai** [comment]
请忽略，是我自己错了。
