### ISSUE TITLE
webstorm配置eslint不行

### ISSUE THREAD

**Issue by xxaxx99** [antdv-pro/antdv-pro#145]
Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

**Comment by xxaxx99** [comment]
改用这个配置后还是不行

**Comment by xxaxx99** [comment]
报错说的是不能识别这个参数但是eslint的配置文件本来就就没这个参数

**Comment by aibayanyu20** [comment]
降级到eslint@8.55或者参考最新版本https://github.com/antdv-pro/antdv-pro/commit/c11224e59c68a9c8017a735ca73d50504539305e

**Comment by xxaxx99** [comment]
> 降级到eslint@8.55或者参考最新版本[c11224e](https://github.com/antdv-pro/antdv-pro/commit/c11224e59c68a9c8017a735ca73d50504539305e)

这个是最新版本的报这个错

**Comment by aibayanyu20** [comment]
package.json看一下

**Comment by xxaxx99** [comment]
> package.json看一下
![image](https://github.com/antdv-pro/antdv-pro/assets/129018645/a49e5b86-cee2-4b13-80fc-717cbf20f49d)

**Comment by xxaxx99** [comment]
> package.json看一下

![image](https://github.com/antdv-pro/antdv-pro/assets/129018645/90a51f1b-6ecd-4c23-b0cb-620036f40790)

**Comment by aibayanyu20** [comment]
发一个全的

**Comment by xxaxx99** [comment]
> 发一个全的

{
  "name": "antdv-pro",
  "type": "module",
  "version": "1.0.1",
  "packageManager": "pnpm@8.10.0",
  "author": "aibayanyu <aibayanyu@qq.com>",
  "repository": "antdv-pro/antdv-pro",
  "scripts": {
    "dev": "mist",
    "build": "vue-tsc && mist build",
    "clear:vercel": "rm -rf ./vercel.json",
    "build:vercel": "run-s clear:vercel build:nitro",
    "build:nitro": "mist build nitro",
    "start:nirto": "node .output/server/index.mjs",
    "preview": "mist preview",
    "lint": "eslint src --fix",
    "typecheck": "vue-tsc --noEmit",
    "bump:patch": "changelogen --bump --output CHANGELOG.md --release",
    "bump:minor": "changelogen --bump --output CHANGELOG.md --release --minor",
    "bump:major": "changelogen --bump --output CHANGELOG.md --release --major",
    "prepare": "husky install",
    "dir-tree": "esno ./scripts/dir-tree",
    "gen:uno": "esno ./scripts/gen-unocss",
    "toJS": "esno scripts/to-js"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^7.0.1",
    "@antv/g2plot": "^2.4.31",
    "@antv/l7": "^2.20.13",
    "@ctrl/tinycolor": "^4.0.2",
    "@v-c/utils": "^0.0.26",
    "@vueuse/core": "^10.7.1",
    "ant-design-vue": "^4.0.8",
    "axios": "^1.6.3",
    "dayjs": "^1.11.10",
    "lodash-es": "^4.17.21",
    "mitt": "^3.0.1",
    "pinia": "^2.1.7",
    "vue": "^3.4.3",
    "vue-i18n": "^9.8.0",
    "vue-router": "^4.2.5"
  },
  "devDependencies": {
    "@commitlint/cli": "^18.4.3",
    "@commitlint/config-conventional": "^18.4.3",
    "@mistjs/cli": "0.0.1-beta.6",
    "@antfu/eslint-config": "^2.6.1",
    "@mistjs/vite-plugin-preload": "^0.0.1",
    "@types/fs-extra": "^11.0.4",
    "@types/lodash": "^4.14.202",
    "@types/lodash-es": "^4.17.12",
    "@types/node": "^20.10.6",
    "@types/treeify": "^1.0.3",
    "@vitejs/plugin-vue": "^5.0.2",
    "@vitejs/plugin-vue-jsx": "^3.1.0",
    "@vue/test-utils": "^2.4.3",
    "antdv-component-resolver": "^1.0.7",
    "antdv-style": "0.0.1-beta.2",
    "changelogen": "^0.5.5",
    "cross-env": "^7.0.3",
    "directory-tree": "^3.5.1",
    "esbuild": "^0.19.11",
    "eslint": "^8.56.0",
    "esno": "^0.17.0",
    "execa": "^8.0.1",
    "fs-extra": "^11.2.0",
    "husky": "^8.0.3",
    "jsdom": "^22.1.0",
    "less": "^4.2.0",
    "lint-staged": "^14.0.1",
    "lodash": "^4.17.21",
    "nitropack": "^2.8.1",
    "npm-run-all": "^4.1.5",
    "picocolors": "^1.0.0",
    "treeify": "^1.1.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3",
    "unocss": "^0.57.7",
    "unocss-preset-chinese": "^0.3.0",
    "unocss-preset-ease": "^0.0.3",
    "unplugin-auto-import": "^0.16.7",
    "unplugin-config": "^0.1.4",
    "unplugin-vue-components": "^0.25.2",
    "vite": "^5.0.10",
    "vitest": "^0.34.6",
    "vue-tsc": "^1.8.27"
  },
  "lint-staged": {
    "**/*.{vue,ts,js,jsx,tsx}": "eslint src --fix"
  }
}

**Comment by xxaxx99** [comment]
> 降级到eslint@8.55或者参考最新版本[c11224e](https://github.com/antdv-pro/antdv-pro/commit/c11224e59c68a9c8017a735ca73d50504539305e)

换了8.55.0还是同样的问题

**Comment by xxaxx99** [comment]
> 降级到eslint@8.55或者参考最新版本[c11224e](https://github.com/antdv-pro/antdv-pro/commit/c11224e59c68a9c8017a735ca73d50504539305e)

降级后可以8.56版本好像是不行的

**Comment by aibayanyu20** [comment]
可以加我一下微信远程看一下，我这边没有你这样的问题

**Comment by aibayanyu20** [comment]
aibayanyu20

**Comment by xxaxx99** [comment]
> aibayanyu20

搜不到用户不存在

**Comment by aibayanyu20** [comment]
aibayanayu2022
