### ISSUE TITLE
顶部LOGO区域的样式问题

### ISSUE THREAD

**Issue by mynetfan** [antdv-pro/antdv-pro#152]
建议左上角LOGO区域显示的标题能够固定一个最大宽度（建议混合布局模式下这个宽度应与左侧菜单宽度相同），如果标题长度超出这个区域不应自动换行。
例子1：混合布局且开始自动分割菜单时，LOGO区域与左侧菜单区域宽度不一致，且顶部菜单的横向位置取决于标题的长度，这不太合理
![image](https://github.com/antdv-pro/antdv-pro/assets/17241274/9f37c4fc-333c-4f14-9751-e9381975fdc9)
例子2：标题较长时，顶部布局模式下LOGO区域完全看不到标题文字
![image](https://github.com/antdv-pro/antdv-pro/assets/17241274/60404fdf-ee43-4374-b759-e514fa528ca0)
例子3：标题较长时，左侧布局模式下LOGO区域的标题自动换行不和谐
![image](https://github.com/antdv-pro/antdv-pro/assets/17241274/58510353-5116-4253-a3f0-9edff7c9b970)

**Comment by kaivanwong** [comment]
例子1：

顶部布局和混合布局使用的是 min-width，基于该设计，宽度与 menu 不相同，合理；

如果你需要的话，你可以通过如下代码实现

![image](https://github.com/antdv-pro/antdv-pro/assets/47177021/532d674b-a422-4947-8e2b-1010029fc57f)

例子2：

未能复现，可能被修复，或者提供代码示例地址

例子3：

已提交 PR (#154)
