### ISSUE TITLE
点击菜单页面不会跳转 需要重新刷新一下才有用   过一会再点击又跳转不了

### ISSUE THREAD

**Issue by zoujinglong666** [antdv-pro/antdv-pro#168]
<img width="1359" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/83895241/1e1475a2-5d76-422b-bcb3-4b77b78c21c8">

**Comment by pansent** [comment]
> <img alt="image" width="1359" src="https://private-user-images.githubusercontent.com/83895241/311499807-1e1475a2-5d76-422b-bcb3-4b77b78c21c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzUwNDgsIm5iZiI6MTcxMDA3NDc0OCwicGF0aCI6Ii84Mzg5NTI0MS8zMTE0OTk4MDctMWUxNDc1YTItNWQ3Ni00MjJiLWJjYjMtNGI3N2I3OGMyMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEyNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMzY4ZmU4NWE2MTNjZjdiZjBjNDE0ZmZhZWRlMDMzZjZhNDQ4NDczNGJhMjJiNjQ4YzFmYThiMzMzNDkzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBZLMudt06MPG-50rk1Ftd1iARQTyHN31qd6nNXHyVo">

看下是不是<Transition>的问题，在该标签内加层div就行

**Comment by zoujinglong666** [comment]
> > <img alt="image" width="1359" src="https://private-user-images.githubusercontent.com/83895241/311499807-1e1475a2-5d76-422b-bcb3-4b77b78c21c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzUwNDgsIm5iZiI6MTcxMDA3NDc0OCwicGF0aCI6Ii84Mzg5NTI0MS8zMTE0OTk4MDctMWUxNDc1YTItNWQ3Ni00MjJiLWJjYjMtNGI3N2I3OGMyMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEyNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMzY4ZmU4NWE2MTNjZjdiZjBjNDE0ZmZhZWRlMDMzZjZhNDQ4NDczNGJhMjJiNjQ4YzFmYThiMzMzNDkzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBZLMudt06MPG-50rk1Ftd1iARQTyHN31qd6nNXHyVo">
> 
> 看下是不是的问题，在该标签内加层div就行
没用

**Comment by aibayanyu20** [comment]
提供一个具体的复现步骤，我测试了一下没有复现你说的问题
