### ISSUE TITLE
全局样式造成antdv库功能失效

### ISSUE THREAD

**Issue by webarn** [antdv-pro/antdv-pro#177]
在 `src/assets/styles/reset.css`文件下，设置了body样式`overflow: hidden;`, 在这中情况下 `a-table` 组件如果使用 `sticky=true` 的 情况下,在table数据需要滚动屏幕的时候， 底部的滚动条回重复，然后点击后会消失 
<img width="1406" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/23495159/b7a24066-8c48-4d3e-abb3-f1121ccab464">

**Comment by aibayanyu20** [comment]
https://github.com/vueComponent/ant-design-vue/issues/7521
