### ISSUE TITLE
菜单路由问题

### ISSUE THREAD

**Issue by zhangqinglei1** [antdv-pro/antdv-pro#191]
我并不是一个非常专业的前端开发，目前遇到一个问题，目前我得系统核心菜单是由后台配置的，但是也会需要前端的路由配置，比如用户跳转个人中心，比如新增功能等等，怎么把后端菜单和前端路由结合起来呢

**Comment by aibayanyu20** [comment]
可以在static-router配置

**Comment by zhangqinglei1** [comment]
感谢已解决
