### ISSUE TITLE
ESlint错误问题

### ISSUE THREAD

**Issue by zhangqinglei1** [antdv-pro/antdv-pro#192]
提交git，然后报错如下
已设置启用自己的eslint但是还是报错

Could not parse lint-staged config.
✖ Validation Error:
  Invalid value for 'linters': {
  '*.{js,json,ts}': [ 'prettier --write', 'git add' ],
  '*.md': [ 'markdown-toc -i', 'prettier --write', 'git add' ]
}
  Advanced configuration has been deprecated.
✖ Validation Error:
  Invalid value for 'ignore': [ 'dist/**', 'mod.js' ]
  Advanced configuration has been deprecated.
See https://github.com/okonet/lint-staged#configuration.
⚠ Detected incorrect braces with only single value: `*.{ts}`. Reformatted as: `*.ts`
⚠ Detected incorrect braces with only single value: `*.{ts}`. Reformatted as: `*.ts`
⚠ Detected incorrect braces with only single value: `*.{ts}`. Reformatted as: `*.ts`
⚠ Detected incorrect braces with only single value: `*.{ts}`. Reformatted as: `*.ts`
Could not parse lint-staged config.
✖ Validation Error:
  Invalid value for 'linters': {
  '*.{js,json,ts}': [ 'prettier --write', 'git add' ],
  '*.md': [ 'markdown-toc -i', 'prettier --write', 'git add' ]
}
  Advanced configuration has been deprecated.
✖ Validation Error:
  Invalid value for 'ignore': [ 'dist/**', 'mod.js' ]
  Advanced configuration has been deprecated.
See https://github.com/okonet/lint-staged#configuration.
Could not parse lint-staged config.
✖ Validation Error:
  Invalid value for 'linters': {
  '*.{js,json,ts}': [ 'prettier --write', 'git add' ],
  '*.md': [ 'markdown-toc -i', 'prettier --write', 'git add' ]
}
  Advanced configuration has been deprecated.
✖ Validation Error:
  Invalid value for 'ignore': [ 'dist/**', 'mod.js' ]
  Advanced configuration has been deprecated.
See https://github.com/okonet/lint-staged#configuration.
Could not parse lint-staged config.
✖ Validation Error:
  Invalid value for 'linters': {
  '*.{js,json,ts}': [ 'prettier --write', 'git add' ],
  '*.md': [ 'markdown-toc -i', 'prettier --write', 'git add' ]
}
  Advanced configuration has been deprecated.
✖ Validation Error:
  Invalid value for 'ignore': [ 'dist/**', 'mod.js' ]
  Advanced configuration has been deprecated.
See https://github.com/okonet/lint-staged#configuration.
husky - pre-commit script failed (code 1)

**Comment by aibayanyu20** [comment]
我试了一下框架，没报错，是不是你自己的prettier影响的，框架默认没有prettier
