### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by YihaoCCC** [antdv-pro/antdv-pro#2]
`pnpm dev ` 启动后访问报错
![image](https://github.com/antdv-pro/antdv-pro/assets/87639931/5785d694-0e1a-46ab-a42c-22c68d0571c1)

进入servers目录后执行 ` pnpm run dev `
等待一会自动执行成功了

![image](https://github.com/antdv-pro/antdv-pro/assets/87639931/50cf6eb6-ede3-45ab-b5dc-5e247ff5fd6d)

**Comment by aibayanyu20** [comment]
电脑系统
