### ISSUE TITLE
固定多标签打开在侧边栏模式和混合布局下有问题

### ISSUE THREAD

**Issue by lis216** [antdv-pro/antdv-pro#205]
1：侧边栏展开收缩动画消失 2：右侧滚动条展示被覆盖

**Comment by aibayanyu20** [comment]
第一个问题没有复现

**Comment by lis216** [comment]
![Uploading PixPin_2024-11-18_15-46-26.gif…]()

**Comment by lis216** [comment]
> 第一个问题没有复现

![PixPin_2024-11-18_15-46-26](https://github.com/user-attachments/assets/0fe728b3-6715-461b-a7a3-0f8d17f9a1f3)

**Comment by lis216** [comment]
> 第一个问题没有复现

看这个gif 多标签栏  两个问题都出现了
