### ISSUE TITLE
谁在用Antdv Pro

### ISSUE THREAD

**Issue by aibayanyu20** [antdv-pro/antdv-pro#48]
如果你的公司或者个人的开源项目有在使用我们的项目做为基础框架进行二次开发，
您这里在这里留下使用过的脚印

* 【公司名称或开源项目名称】
* 【应用项目介绍】
* 【如果允许可以公开官网地址】

**Comment by TsMask** [comment]
项目：基于 Ant-Design-Vue + Vue3 的管理系统
介绍：ruoyi后台功能的实现，布局采用vue版本 [pro-components](https://github.com/vueComponent/pro-components)
地址：https://gitee.com/TsMask/mask_antd_vue3

**Comment by TsMask** [comment]
> 项目：基于 Ant-Design-Vue + Vue3 的管理系统 介绍：ruoyi后台功能的实现，布局采用vue版本 [pro-components](https://github.com/vueComponent/pro-components) 地址：https://gitee.com/TsMask/mask_antd_vue3

能否将pro-components更新到V4版本，我提交pr都没人合并。这边的的是另外发布新pro-components还是合并到那个仓库去发布呢？

**Comment by aibayanyu20** [comment]
> pro-components

团队成员目前都是在职维护开源，所以并没有很多的精力去维护这个项目，所以目前来看应该是停更了的，如果您有需要可以直接fork主分支，进行二开发布，我们这边目前已经暂停V4版本的开发计划了

**Comment by TsMask** [comment]
> > pro-components
> 
> 团队成员目前都是在职维护开源，所以并没有很多的精力去维护这个项目，目前来看应该是停更了的，如果您有需要可以直接fork主分支，进行二开发布，我们这边目前已经暂停V4版本的开发计划了

我项目再用，后续升级v4。我能加入[pro-components](https://github.com/vueComponent/pro-components)仓库和给我进行npm的发布权限吗？pro-components仓库人员都没时间合并pr发布新版本，你帮我联系下仓库管理员可以不？我wx：li_340

**Comment by aibayanyu20** [comment]
https://github.com/vueComponent/pro-components/tree/feat-v4 你可以提交到这个分支，我帮你合并和发布

> > > pro-components
> > 
> > 
> > 团队成员目前都是在职维护开源，所以并没有很多的精力去维护这个项目，目前来看应该是停更了的，如果您有需要可以直接fork主分支，进行二开发布，我们这边目前已经暂停V4版本的开发计划了
> 
> 我项目再用，后续升级v4。我能加入[pro-components](https://github.com/vueComponent/pro-components)仓库和给我进行npm的发布权限吗？pro-components仓库人员都没时间合并pr发布新版本，你帮我联系下仓库管理员可以不？我wx：li_340

**Comment by TsMask** [comment]
> https://github.com/vueComponent/pro-components/tree/feat-v4 你可以提交到这个分支，我帮你合并和发布
> 
> > > > pro-components
> > > 
> > > 
> > > 团队成员目前都是在职维护开源，所以并没有很多的精力去维护这个项目，目前来看应该是停更了的，如果您有需要可以直接fork主分支，进行二开发布，我们这边目前已经暂停V4版本的开发计划了
> > 
> > 
> > 我项目再用，后续升级v4。我能加入[pro-components](https://github.com/vueComponent/pro-components)仓库和给我进行npm的发布权限吗？pro-components仓库人员都没时间合并pr发布新版本，你帮我联系下仓库管理员可以不？我wx：li_340

关于v3的提交你那能合并去发新版本3.2.5吗？

**Comment by aibayanyu20** [comment]
> > [vueComponent/pro-components@`feat-v4`](https://github.com/vueComponent/pro-components/tree/feat-v4?rgh-link-date=2023-10-21T15%3A18%3A28Z) 你可以提交到这个分支，我帮你合并和发布
> > > > > pro-components
> > > > 
> > > > 
> > > > 团队成员目前都是在职维护开源，所以并没有很多的精力去维护这个项目，目前来看应该是停更了的，如果您有需要可以直接fork主分支，进行二开发布，我们这边目前已经暂停V4版本的开发计划了
> > > 
> > > 
> > > 我项目再用，后续升级v4。我能加入[pro-components](https://github.com/vueComponent/pro-components)仓库和给我进行npm的发布权限吗？pro-components仓库人员都没时间合并pr发布新版本，你帮我联系下仓库管理员可以不？我wx：li_340
> 
> 关于v3的提交你那能合并去发新版本3.2.5吗？

已合并并发版，如果有时间可以考虑做一下v4版本的pro-layout  https://github.com/antdv-pro/layout   可以提交到这个仓库

**Comment by TsMask** [comment]
感谢合并发版3.2.5，后续npmjs包@ant-design-vue/pro-layout发布改pro-layout https://github.com/antdv-pro/layout 了吗？

原先的pro-layout https://github.com/vueComponent/pro-components是停止维护了？

> 这个帖子信息要给你删除掉吗？

**Comment by aibayanyu20** [comment]
我们建立了一个社区，会专门做一些通用组件，不与官方挂钩更容易维护，目前官方成员基本上没有时间去做这件事情，如果有意愿参与进来可以加我微信aibayanyu2022
