### ISSUE TITLE
菜单展开和关闭图标貌似反了

### ISSUE THREAD

**Issue by Prism57** [antdv-pro/antdv-pro#53]
B站刷到过来看看，不怎么熟悉PR，就提issues吧。
如题，按钮点击的应该是预期行为，所以关闭的时候应该展示展开的按钮，展开的时候应该展示关闭的按钮。
unfold和fold
另外这两个图标的大小也不一致，一个14另一个是16

**Comment by kirklin** [comment]
感谢你提出这个问题！我已经注意到了图标大小的不一致以及图标反了的问题
但是图标大小不一致是正确的。
