### ISSUE TITLE
 i18n规则中包含@符号导致控制台报错

### ISSUE THREAD

**Issue by kirklin** [antdv-pro/antdv-pro#60]
### Issue 描述：
在编写 i18n 国际化规则时，发现如果语句中包含 "@" 符号，会导致控制台报错。
创建一个包含 "@" 符号的 i18n 规则，例如：
```json
{
  "error_message": "发生了一个@错误"
}
```
在应用中触发使用该 i18n 规则的场景，比如显示错误提示。
### 预期行为：
预期应用能够正确读取 i18n 规则中包含 "@" 符号的文本，并在界面上展示对应的翻译文本，而不会导致控制台报错。

### 实际行为：
当前应用在加载包含 "@" 符号的 i18n 规则时，控制台报告错误，可能类似如下的错误信息：
![c5f99e49d44561e8ff76cd28ba71812](https://github.com/antdv-pro/antdv-pro/assets/17453452/719befb0-1789-4d66-aa63-fa06ea8192f1)

**Comment by windlil** [comment]
貌似得用这种格式才不会报错，这种写法{}内得是单引号，和项目的eslint配置有点冲突了。
```json
{
  "error_message": "发生了一个{'@'}错误"
}
```
还可以这么写：
```json
{
  "error_message": "发生了一个{0}错误"
}
```
```vue
<p>{{ t('error_message', ['@']) }}</p>
```
说明文档 https://kazupon.github.io/vue-i18n/zh/guide/formatting.html#%E5%88%97%E8%A1%A8%E6%A0%BC%E5%BC%8F

**Comment by kirklin** [comment]
```json
{
  'error_message': '发生了一个{\'@\'}错误'
}
```
