### ISSUE TITLE
主题色配置后 很多场景 配置色并未同步修改 

### ISSUE THREAD

**Issue by wongjull** [antdv-pro/antdv-pro#66]
主题色配置后 很多场景 配置色并未同步修改 
目前已发现的有：
1、首屏加载的loading 图标的颜色 还是蓝色
2、a-button type为link状态时 颜色还是蓝色 应该还有其他类似问题 有时间可以一同检查一下 
辛苦啦

**Comment by aibayanyu20** [comment]
首屏加载loading可以通过自己存储主色样式来实现
button的 link模式通过token中的colorLink、colorLinkHover和colorLinkActive来控制
