### ISSUE TITLE
设置布局时还是会占用元素宽度

### ISSUE THREAD

**Issue by FlayLson** [antdv-pro/antdv-pro#72]
效果：

如下是设置的：
{"title":"Antdv Pro","theme":"inverted","logo":"/logo.svg","collapsed":false,"drawerVisible":true,"colorPrimary":"#1677FF","layout":"side","contentWidth":"Fluid","fixedHeader":true,"fixedSider":false,"splitMenus":false,"header":true,"menu":false,"menuHeader":false,"footer":false,"colorWeak":false,"multiTab":false,"multiTabFixed":false,"keepAlive":true,"accordionMode":false,"headerHeight":48,"copyright":"Antdv Pro Team 2023","animationName":"slide-fadein-right"}

**Comment by aibayanyu20** [comment]
什么会占用元素宽度，可以补张图或者视频么

**Comment by FlayLson** [comment]
![1693272207627](https://github.com/antdv-pro/antdv-pro/assets/73685882/5746e77e-6e46-41c9-883a-3b5f5a6186bd)
