### ISSUE TITLE
增加了a-style-provider后，unocss的样式被覆盖了

### ISSUE THREAD

**Issue by holiy930561** [antdv-pro/antdv-pro#8]
Ap.vue
<template>
  <a-config-provider :theme="theme" :locale="antd">
    <a-style-provider hash-priority="high">
      <TokenProvider>
        <RouterView />
      </TokenProvider>
    </a-style-provider>
  </a-config-provider>
</template>

增加了a-style-provider后，unocss的样式被覆盖了
![image](https://github.com/antdv-pro/antdv-pro/assets/63273780/a513203d-1db2-4958-91dd-baa05eab71fa)

**Comment by aibayanyu20** [comment]
样式优先级导致的问题，这个我看看有什么好的解决方案

**Comment by aibayanyu20** [comment]
参考方案：[主题降级](https://docs.antdv-pro.com/guide/theme-style.html#%E6%A0%B7%E5%BC%8F%E9%99%8D%E7%BA%A7)

**Comment by holiy930561** [comment]
unocss mode: vue-scoped暂时解决了，我再试试你的方案
