### ISSUE TITLE
新功能征集！！！

### ISSUE THREAD

**Issue by aibayanyu20** [antdv-pro/antdv-pro#9]
如果大家在使用的过程中感觉某个功能可能会比较通用或者有自己的一些需求，您可以在下面进行留言，我们会进行确认需求的可行性和通用性，会逐步的为我们的开源项目新增一些常用的功能。

提交模板：

功能简述：可编辑表格功能
功能描述：希望新增可编辑表格的演示功能....（会优先考虑描述详细且合理的需求）

## 需求列表

- [x] #13 @aibayanyu20 
- [x] #12 @aibayanyu20 
- [x] #10 @aibayanyu20 
- [x] #14 @Spectature 
- [x] #15 @Spectature 
- [x] #17 @Spectature 
- [x] #16 @kirklin 
- [x] #18 @kirklin 
- [x] #19 @kirklin 
- [x] #20 @aibayanyu20 
- [x] #21 @aibayanyu20 
- [x] #22 @aibayanyu20 
- [x] #24 @aibayanyu20 
- [x] #23 @windlil
- [x] #25 @windlil 
- [x] #26 @kirklin 
- [x] #27 @windlil 
- [x] #28 @kirklin 
- [x] #29 @kirklin 
- [x] #30 @adekang 
- [x] #31 @adekang 
- [x] #32 @adekang 
- [x] #33 @windlil 
- [x] #34 @windlil 
- [ ] #105 @wcySpring 

# 需求认领

[参考演示站点](https://preview.pro.ant.design/)

如果你想开发其中某一个功能，请在下方评论认领功能例如多功能表格：

* 多功能表格示例

认领后我会将当前的功能分发给你，请尽量在两周内完成，如果长时间完不成我们将会对任务进行二次分发

**Comment by Lingtin** [comment]
功能简述：表格列表功能
功能描述：希望新增，表格列表（可多选、并跨页）可配置表头（列定制、筛选操作），搜索条件（搜索、清空按钮，多条件可以显示隐藏），基础分页功能等，算是一个比较通用的功能吧

**Comment by aibayanyu20** [comment]
> 功能简述：表格列表功能 功能描述：希望新增，表格列表（可多选、并跨页）可配置表头（列定制、筛选操作），搜索条件（搜索、清空按钮，多条件可以显示隐藏），基础分页功能等，算是一个比较通用的功能吧

可以在计划中了。会有一个单独的库叫pro-components来实现表格和表单的功能，类比[ant-design-procomponents](https://procomponents.ant.design/)

**Comment by xingyuv** [comment]
1. 增加 prettier 及一些代码规范的内容
2. layout 增加 breadcrumb
3. 页面切换的效果动态配置

**Comment by aibayanyu20** [comment]
> 1. 增加 prettier 及一些代码规范的内容
> 2. layout 增加 breadcrumb
> 3. 页面切换的效果动态配置
感谢建议：
1. 因为prettier格式化会存在一些问题，目前并没有打算加入，如确实有需要，像jsx这种我们也提供了一个规范库，`pnpm add @mistjs/eslint-config-vue-jsx prettier -Dw`来支持prettier格式化，代码规范后面会在文档中补全

2. 目前面包屑跟随pagecontainer组件，这个需要看后期的计划做实现
3. #10

**Comment by kai2128** [comment]
功能简述：添加 Dockerfile 
功能描述：希望可以使用 docker 部署

**Comment by aibayanyu20** [comment]
> 功能简述：添加 Dockerfile 功能描述：希望可以使用 docker 部署

添加了

**Comment by djkloop** [comment]
前面看vben的源码貌似做成了monorepo，各种lint 配置都拆开了。 这个库后续也会改成这样吗？会把pro组件和这个仓库下吗？

**Comment by aibayanyu20** [comment]
> 前面看vben的源码貌似做成了monorepo，各种lint 配置都拆开了。 这个库后续也会改成这样吗？会把pro组件和这个仓库下吗？

不会，会有一个单独的pro的组件库，强制开发者使用pnpm我认为是不好的一种体验，目前我们的项目在完全集成后端的情况下是可以脱离pnpm使用npm和yarn去部署这样会更灵活一些。

**Comment by glennliao** [comment]
> > 功能简述：表格列表功能 功能描述：希望新增，表格列表（可多选、并跨页）可配置表头（列定制、筛选操作），搜索条件（搜索、清空按钮，多条件可以显示隐藏），基础分页功能等，算是一个比较通用的功能吧
> 
> 可以在计划中了。会有一个单独的库叫pro-components来实现表格和表单的功能，类比[ant-design-procomponents](https://procomponents.ant.design/)

是否还可以将layout也放到这里 做个pro-layout呢

**Comment by baixjian** [comment]
是否可以支持登录后重定向到某个页面，例如打开https://www.antdv-pro.com/menu/menu1，未登录跳https://www.antdv-pro.com/login?redirect=/menu/menu1，点击登录跳转到https://www.antdv-pro.com/menu/menu1

**Comment by aibayanyu20** [comment]
> 是否可以支持登录后重定向到某个页面，例如打开[https://www.antdv-pro.com/menu/menu1，未登录跳https://www.antdv-pro.com/login?redirect=/menu/menu1，点击登录跳转到https://www.antdv-pro.com/menu/menu1](https://www.antdv-pro.com/menu/menu1%EF%BC%8C%E6%9C%AA%E7%99%BB%E5%BD%95%E8%B7%B3https://www.antdv-pro.com/login?redirect=/menu/menu1%EF%BC%8C%E7%82%B9%E5%87%BB%E7%99%BB%E5%BD%95%E8%B7%B3%E8%BD%AC%E5%88%B0https://www.antdv-pro.com/menu/menu1)

支持了

**Comment by windlil** [comment]
- 【页面】同步卡片列表

**Comment by kirklin** [comment]
- 【页面】同步基础详情页
- 【页面】同步基础表单功能
- 【页面】同步分步表单功能
- 【页面】同步结果页成功页
- 【页面】同步结果页失败页

**Comment by songsong0707** [comment]
*【页面】同步标准列表

**Comment by windlil** [comment]
- 【页面】同步标准列表
-  【页面】同步高级详情页

**Comment by Spectature** [comment]
- 【页面】同步分析页功能
- 【页面】同步监控页功能
- 【页面】同步工作台功能

**Comment by Lingtin** [comment]
功能简述：页签缓存功能
功能描述：希望新增，打开多个页签时，刷新浏览器页面时不会丢失当前打开的页签签焦点和其它页签状态。

**Comment by windlil** [comment]
- https://github.com/antdv-pro/antdv-pro/issues/33
- https://github.com/antdv-pro/antdv-pro/issues/34

**Comment by baixjian** [comment]
简版会持续更新吗

**Comment by aibayanyu20** [comment]
> 简版会持续更新吗


等做完所有页面会同步一个终版，正常就只会修修bug，不会再更新了

**Comment by baixjian** [comment]
<img width="769" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/109275788/01c850d5-e426-4ff4-aad1-9143a5a246f0">
tab页签这个功能也蛮不错的

**Comment by aibayanyu20** [comment]
> <img width="769" alt="image" src="https://github.com/antdv-pro/antdv-pro/assets/109275788/01c850d5-e426-4ff4-aad1-9143a5a246f0">
> 
> tab页签这个功能也蛮不错的

我们也支持多页签

**Comment by perintery** [comment]
1. 根据 swagger.json 生成所有的接口文件和  类型定义
2. 抽取中文  到 国际化的方案.

**Comment by lovesL** [comment]
> > 功能简述：表格列表功能 功能描述：希望新增，表格列表（可多选、并跨页）可配置表头（列定制、筛选操作），搜索条件（搜索、清空按钮，多条件可以显示隐藏），基础分页功能等，算是一个比较通用的功能吧
> 
> 可以在计划中了。会有一个单独的库叫pro-components来实现表格和表单的功能，类比[ant-design-procomponents](https://procomponents.ant.design/)
同求 急需

**Comment by aibayanyu20** [comment]
> > > 功能简述：表格列表功能 功能描述：希望新增，表格列表（可多选、并跨页）可配置表头（列定制、筛选操作），搜索条件（搜索、清空按钮，多条件可以显示隐藏），基础分页功能等，算是一个比较通用的功能吧
> > 
> > 
> > 可以在计划中了。会有一个单独的库叫pro-components来实现表格和表单的功能，类比[ant-design-procomponents](https://procomponents.ant.design/)
> > 同求 急需

因为antdv4的一些生态还不是很全，现在在补生态库`antdv-style`，等做完这个库会再做响应的开发

**Comment by wcySpring** [comment]
是否考虑增加 svg 模块 如果需要的话 我很愿意将 

`unplugin-icons`  `vite-plugin-svg-icons` `@iconify/vue` 

集成进去虽然关于他们优缺点

`unplugin-icons` , 能够识别本地 svg 文件，并且可以配合 iconify 图标库，利用 `unplugin-auto-import` 可以实现自动下载 使用到的 iconify 图标集

`vite-plugin-svg-icons`, 针对本地 svg 图标插件管理，通过配合 封装的 svg 组件，利用其精灵图的特性可以优化 svg 数量

`@iconify/vue`,一个已经封装好的 vue 组件用来直接使用  iconify 图标库，支持cdn 加载图片，并且会将加载后的图标存储在本地，也可以使用 本地下载好的 iconify 图标库

**Comment by aibayanyu20** [comment]
> 是否考虑增加 svg 模块 如果需要的话 我很愿意将
> 
> `unplugin-icons` `vite-plugin-svg-icons` `@iconify/vue`
> 
> 集成进去虽然关于他们优缺点
> 
> `unplugin-icons` , 能够识别本地 svg 文件，并且可以配合 iconify 图标库，利用 `unplugin-auto-import` 可以实现自动下载 使用到的 iconify 图标集
> 
> `vite-plugin-svg-icons`, 针对本地 svg 图标插件管理，通过配合 封装的 svg 组件，利用其精灵图的特性可以优化 svg 数量
> 
> `@iconify/vue`,一个已经封装好的 vue 组件用来直接使用 iconify 图标库，支持cdn 加载图片，并且会将加载后的图标存储在本地，也可以使用 本地下载好的 iconify 图标库

把unplugin-icons集成进来吧，vite-plugin-svg-icons这个先保留，记得在文档库https://github.com/antdv-pro/docs中描述一下使用方式

**Comment by kirklin** [comment]
> 是否考虑增加 svg 模块 如果需要的话 我很愿意将 
> 
> `unplugin-icons`  `vite-plugin-svg-icons` `@iconify/vue` 
> 
> 集成进去虽然关于他们优缺点
> 
> `unplugin-icons` , 能够识别本地 svg 文件，并且可以配合 iconify 图标库，利用 `unplugin-auto-import` 可以实现自动下载 使用到的 iconify 图标集
> 
> `vite-plugin-svg-icons`, 针对本地 svg 图标插件管理，通过配合 封装的 svg 组件，利用其精灵图的特性可以优化 svg 数量
> 
> `@iconify/vue`,一个已经封装好的 vue 组件用来直接使用  iconify 图标库，支持cdn 加载图片，并且会将加载后的图标存储在本地，也可以使用 本地下载好的 iconify 图标库

我不建议添加，因为unocss已经支持这部分功能了。没必要再引入额外的库
https://unocss.dev/presets/icons

**Comment by wcySpring** [comment]
增加一下prettier 配置文件，因为项目的保存 总是和我本地的冲突，读取不到项目根的

**Comment by Winna-wnn** [comment]
是否考虑集成微前端方案?
