### ISSUE TITLE
这个三级页面导航，在这个项目中使用的是状态切换，但是更多时候使用的 RouterView（有路由可以复制链接后直接到具体的页面） ，这个可以优化吗？

### ISSUE THREAD

**Issue by helloshaohua** [antdv-pro/antdv-pro#94]
![image](https://github.com/antdv-pro/antdv-pro/assets/53924395/e23aafc0-82a5-437a-b630-f512743f89c6)

**Comment by helloshaohua** [comment]
![image](https://github.com/antdv-pro/antdv-pro/assets/53924395/a052a5e4-98ad-44a0-a649-cf696b363d96)

**Comment by aibayanyu20** [comment]
这个后续应该是可以实现的，不过目前来看https://github.com/vuejs/router/issues/626 这个问题不解决不太好处理这种情况

**Comment by helloshaohua** [comment]
@aibayanyu20 不应该是 [vuejs/roouter#626](https://github.com/vuejs/router/issues/626) 这个问题吧，ant design vue pro v2 都有实现，V3PRO 版本也有实现


![image](https://github.com/antdv-pro/antdv-pro/assets/53924395/78d90bf4-f417-4e04-978b-b1026cc037c3)
![image](https://github.com/antdv-pro/antdv-pro/assets/53924395/3635fe02-aee3-47a2-95ee-2c1ca0708978)

**Comment by aibayanyu20** [comment]
因为他的三级保活没办法用，所以可以，我们现在也可以实现，参考 https://www.antdv-pro.com/list/search-list/articles

**Comment by aibayanyu20** [comment]
如果你不需要嵌套路由你可以使用basicRouteMap.RouterView，更直接一些就把common/route-view的ParentCompConsumer组件注释掉
