### ISSUE TITLE
需要一些样式风格修复

### ISSUE THREAD

**Issue by W54321qiqqi** [antdv-pro/antdv-pro#95]
![image](https://github.com/antdv-pro/antdv-pro/assets/107609331/d4df7299-69f4-46bc-97f1-fa96cd8aa649)
![image](https://github.com/antdv-pro/antdv-pro/assets/107609331/ce792acc-5e5d-4bd5-babe-be0b8f1ea2ce)

这些mini图表没有适配

**Comment by aibayanyu20** [comment]
get @Spectature

**Comment by Spectature** [comment]
> get @Spectature

我看看
